# Generated by Django 3.1.3 on 2020-12-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('CPF', models.PositiveBigIntegerField()),
                ('Email', models.CharField(max_length=60)),
                ('Phone', models.PositiveBigIntegerField()),
                ('End', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='productsitens',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productsitens',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
