# Generated by Django 3.1.3 on 2020-12-23 00:25

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201221_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='nameCustomers',
        ),
        migrations.RenameField(
            model_name='productsitens',
            old_name='name',
            new_name='nameProducts',
        ),
        migrations.AddField(
            model_name='productsitens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=API.models.uploadImageProducts),
        ),
    ]
