# Generated by Django 3.1.2 on 2020-12-29 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsitens',
            name='image',
        ),
        migrations.AddField(
            model_name='productsitens',
            name='imageProducts',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
