# Generated by Django 3.1.2 on 2020-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201229_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsitens',
            name='imageProducts',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
