# Generated by Django 3.1.2 on 2020-12-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_productsitens_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCustomersRequest', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('numberRequest', models.PositiveBigIntegerField()),
                ('endCustomersResquest', models.CharField(max_length=60)),
                ('resquestItems', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('shippingMethod', models.CharField(max_length=60)),
            ],
        ),
    ]
