# Generated by Django 3.1.3 on 2021-02-03 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='CPFCustomers',
            field=models.PositiveBigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.PositiveBigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='quantityItens',
            field=models.PositiveBigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='resquestItems',
            field=models.CharField(max_length=255),
        ),
    ]
