# Generated by Django 3.1.3 on 2021-02-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210203_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='CPFCustomers',
            new_name='CPF',
        ),
    ]
