# Generated by Django 3.1.3 on 2021-02-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20210213_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='CPF',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.CharField(max_length=60),
        ),
    ]
